[package]
name = "grafial-ir"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Intermediate representation for Grafial programs"

[dependencies]
grafial-frontend = { path = "../grafial-frontend" }
thiserror.workspace = true

